services:

  # Kafka(KRaft)
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "9102:9102"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9103'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9102,CONTROLLER://0.0.0.0:9103'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://devnogi.ddns.net:9102'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    volumes:
      - /opt/kafka/data:/var/lib/kafka/data
    networks:
      - devnogi-network

  # MinIO
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
    volumes:
      - /opt/infra/minio-data:/data
    command: server /data --address ":9001" --console-address ":9000"
    networks:
      - devnogi-network

  # AuthHeal
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal-prod-1
    restart: unless-stopped
    environment:
      AUTOHEAL_INTERVAL: ${AUTOHEAL_INTERVAL}
      AUTOHEAL_START_PERIOD: ${AUTOHEAL_START_PERIOD}
      AUTOHEAL_DEFAULT_STOP_TIMEOUT: ${AUTOHEAL_DEFAULT_STOP_TIMEOUT}
      DOCKER_SOCK: /var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - devnogi-network
    deploy:
      resources:
        limits:
          memory: ${AUTOHEAL_MEMORY_LIMIT}
        reservations:
          memory: ${AUTOHEAL_MEMORY_RESERVATION}

networks:
  devnogi-network:
    driver: bridge