name: Deploy to On-Premise 2

on:
  push:
    paths:
      - 'docker-compose-prod2.yml'
      - '.github/workflows/deploy-prod2.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose to Server 2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD2_HOST }}
          username: ${{ secrets.PROD2_USER }}
          key: ${{ secrets.PROD2_PEM_KEY }}
          port: ${{ secrets.PROD2_SSH_PORT }}
          source: "docker-compose-prod2.yml"
          target: "/opt/infra/"

      - name: Create .env and Execute Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD2_HOST }}
          username: ${{ secrets.PROD2_USER }}
          key: ${{ secrets.PROD2_PEM_KEY }}
          port: ${{ secrets.PROD2_SSH_PORT }}
          script: |
            mkdir -p /opt/infra
            cd /opt/infra
            
            cat << 'EOF' > .env.infra2
            ${{ secrets.PROD2_ENV_FILE }}
            EOF
            
            docker compose -f docker-compose-prod2.yml --env-file .env.infra2 pull
            docker compose -f docker-compose-prod2.yml --env-file .env.infra2 up -d
            
            docker image prune -f